languageCode: ko-kr
languageLang: ko
defaultContentLanguage: ko
title: 반 스튜디오
description: baanstudio.com
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
outputs:
  home:
    - HTML
    - JSON
    - RSS
  page:
    - HTML