title: 반 스튜디오
description: baanstudio.com

languageCode: ko-kr
languageLang: ko
DefaultContentLanguage: en

languages:
  ko:
    title: 반 스튜디오
  en:
    title: baanstudio
    weight: 1

DisableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
outputs:
  home:
    - HTML
    - JSON
    - RSS
  page:
    - HTML